# ==============================================================================
# End-to-End YOLO Dataset Pipeline - Master Configuration
#
# 이 파일은 3단계 워크플로우에 맞춰 재구성된 프로젝트의 마스터 제어판입니다.
# 각 스크립트는 실행 시 이 파일의 설정을 참조합니다.
# ==============================================================================

# ------------------------------------------------------------------------------
# [전역 설정] 프로젝트 기본 정보 (Global Project Settings)
#
# 모든 워크플로우에서 공통으로 사용되는 기본 정보입니다.
# ------------------------------------------------------------------------------
project_settings:
  # 학습할 객체의 클래스 정의. Key: class_id, Value: class_name
  classes:
    0: 'center_line'
    1: 'obstacle_vehicle'
    2: 'race_traffic_light'
    3: 'checkerboard'

  # 프로젝트에서 사용할 이미지 포맷
  image_format: 'png,jpg,jpeg'


# ==============================================================================
# [Phase 1] 초기 Teacher 모델 구축 워크플로우 설정
# (1_Initial_Teacher_Workflow)
# ==============================================================================
initial_teacher_workflow:
  # [1a] ROS2 Bag 추출 설정
  ros2_bag_extraction:
    # [사용자 수정 필요] 추출할 ros2bag 폴더의 '절대 경로'
    directory: '/home/kdh/Desktop/rosbags/kookmin/8월 11일/mission1'
    image_topic: '/image_raw'
    # 추출된 원본 이미지를 저장할 데이터셋 경로
    output_dir: 'datasets/phase1_extracted'

  # [1b] 수동 라벨링을 마친 초기 데이터셋 경로
  # output_dir에서 일부를 라벨링하여 이 폴더로 옮기거나, 이 폴더에서 직접 작업
  initial_labeled_dataset: 'datasets/phase1_initial_labeled'

  # [1c] 데이터 분할 설정
  train_ratio: 0.8  # 학습용 데이터 비율 (80%)

  # [1d] Teacher 모델 학습 설정
  teacher_model_config:
    model_name: 'yolov10m'
    hyperparameters:
      epochs: 1000
      patience: 100
      models:
        yolov8x:
          batch_size: 8
          img_size: 608
        yolov10n:
          batch_size: 32
          img_size: 640
        yolov10s:
          batch_size: 16
          img_size: 640
        yolov10m:
          batch_size: 8
          img_size: 640
        default:
          batch_size: 16
          img_size: 640


# ==============================================================================
# [Phase 2] 준지도 학습 사이클 설정
# (2_Semi_Supervised_Cycle)
# ==============================================================================
semi_supervised_cycle:
  # [2a] 자동 라벨링 대상이 되는, 라벨 없는 대규모 이미지 풀 경로
  unlabeled_pool_dir: 'datasets/phase2_unlabeled_pool'

  # [2a] 자동 라벨링에 사용할 Teacher 모델 가중치 경로
  teacher_model_weights: 'runs/train/yolov10m_on_phase1_initial_labeled/weights/best.pt'
  
  # [2a] 자동 라벨링 시 사용할 신뢰도 임계값
  confidence_threshold: 0.3
  
  # [2b] 자동 라벨링 후 검토/수정한 데이터를 저장할 경로
  reviewed_dataset: 'datasets/phase2_reviewed_data'
  
  # [2c] 재학습 시, 기존 데이터와 새로 검토한 데이터를 합쳐서 저장할 최종 데이터셋 경로
  merged_dataset_for_retrain: 'datasets/phase2_merged_for_retrain'


# ==============================================================================
# [Phase 3] 최종 Student 모델 학습 설정
# (3_Final_Student_Training)
# ==============================================================================
final_student_training:
  # [3a] 최종 학습에 사용할, Phase 2에서 완성된 대규모 데이터셋 경로
  final_dataset_path: 'datasets/phase2_merged_for_retrain'

  # [3a] 최종적으로 학습시킬 Student 모델 설정
  student_model_config:
    # Teacher와 다른, 더 가벼운 모델을 지정할 수 있습니다.
    model_name: 'yolov10s' 
    # 하이퍼파라미터는 Teacher의 것을 사용하거나, 필요시 별도로 정의할 수 있습니다.
    # 예: hyperparameters: { epochs: 500, ... }


# ==============================================================================
# [고급 기능] 액티브 러닝 설정
# (advanced_features)
# ==============================================================================
active_learning:
  # 예측에 사용할 선생님 모델
  weights_path: 'runs/train/yolov10m_result/weights/best.pt'
  # 예측 결과, 특징 등 중간 파일이 저장될 작업 공간
  workspace_dir: 'active_learning_workspace'
  # 최종적으로 선택할 이미지 개수
  selection_size: 100
  # 불확실성 샘플링 신뢰도 구간 (최소, 최대)
  min_confidence: 0.4
  max_confidence: 0.8


# ==============================================================================
# [보조 도구] Tools 기본 설정
# (tools)
# ==============================================================================
tool_defaults:
  # [merge_datasets.py] 기본으로 병합할 데이터셋 목록
  merge_inputs:
    - 'datasets/phase1_initial_labeled'
    - 'datasets/phase2_reviewed_data'

  # [sample_dataset.py] 기본 샘플링 설정
  sampling_source: 'datasets/phase2_merged_for_retrain'
  sampling_ratio: 0.1
  sampling_output: 'datasets/sample_for_test'
